coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 70%

  # Focus on business logic, not generated code
  ignore:
    - "src/QueueDrop.Infrastructure/Migrations/**"
    - "**/*.Designer.cs"
    - "**/obj/**"
    - "**/bin/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
