// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QueueDrop.Infrastructure.Persistence;

#nullable disable

namespace QueueDrop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128055238_AddAuthEntities")]
    partial class AddAuthEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QueueDrop.Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("businesses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A demo business for testing QueueDrop",
                            Name = "Demo Shop",
                            Slug = "demo-shop"
                        });
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.BusinessMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BusinessId")
                        .IsUnique();

                    b.ToTable("business_members", (string)null);
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.MagicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("magic_links", (string)null);
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "IsActive");

                    b.HasIndex("BusinessId", "Slug")
                        .IsUnique();

                    b.ToTable("queues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BusinessId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsPaused = false,
                            Name = "Main Queue",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            Slug = "main-queue"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BusinessId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsPaused = false,
                            Name = "Takeout",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            Slug = "takeout"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BusinessId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsPaused = false,
                            Name = "Bar",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            Slug = "bar"
                        });
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.QueueCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JoinPosition")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PartySize")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PushSubscription")
                        .HasColumnType("text");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ServedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("QueueId", "JoinedAt");

                    b.HasIndex("QueueId", "Status");

                    b.ToTable("queue_customers", (string)null);
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.BusinessMember", b =>
                {
                    b.HasOne("QueueDrop.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueDrop.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.Queue", b =>
                {
                    b.HasOne("QueueDrop.Domain.Entities.Business", "Business")
                        .WithMany("Queues")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("QueueDrop.Domain.Entities.QueueSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("QueueId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowJoinWhenPaused")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("settings_allow_join_when_paused");

                            b1.Property<string>("CalledMessage")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("settings_called_message");

                            b1.Property<int>("EstimatedServiceTimeMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(5)
                                .HasColumnName("settings_estimated_service_time_minutes");

                            b1.Property<int?>("MaxQueueSize")
                                .HasColumnType("integer")
                                .HasColumnName("settings_max_queue_size");

                            b1.Property<int>("NoShowTimeoutMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(5)
                                .HasColumnName("settings_no_show_timeout_minutes");

                            b1.Property<string>("WelcomeMessage")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("settings_welcome_message");

                            b1.HasKey("QueueId");

                            b1.ToTable("queues");

                            b1.WithOwner()
                                .HasForeignKey("QueueId");

                            b1.HasData(
                                new
                                {
                                    QueueId = new Guid("22222222-2222-2222-2222-222222222222"),
                                    AllowJoinWhenPaused = false,
                                    EstimatedServiceTimeMinutes = 5,
                                    NoShowTimeoutMinutes = 5
                                },
                                new
                                {
                                    QueueId = new Guid("33333333-3333-3333-3333-333333333333"),
                                    AllowJoinWhenPaused = false,
                                    EstimatedServiceTimeMinutes = 3,
                                    NoShowTimeoutMinutes = 5
                                },
                                new
                                {
                                    QueueId = new Guid("44444444-4444-4444-4444-444444444444"),
                                    AllowJoinWhenPaused = false,
                                    EstimatedServiceTimeMinutes = 10,
                                    MaxQueueSize = 20,
                                    NoShowTimeoutMinutes = 5
                                });
                        });

                    b.Navigation("Business");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.QueueCustomer", b =>
                {
                    b.HasOne("QueueDrop.Domain.Entities.Queue", null)
                        .WithMany("Customers")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.Business", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("QueueDrop.Domain.Entities.Queue", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
